all:jarvis_demo_setup jarvis_demo_server jarvis_demo_client

ROOTDIR=/data/devel/aroy/jarvis
# Additional places to look for include files.
INCLUDES := -I$(ROOTDIR)/include -I$(ROOTDIR)/util
LIBS := -L$(ROOTDIR)/lib -Wl,-rpath,"$(ROOTDIR)/lib"

EXTRA_LIBS := -lcyclone -lpmemobj -lpmem -lboost_system -lboost_date_time

# Omit the frame pointer unless we are profiling.
ifeq ($(findstring -pg,$(OPT)),)
OMIT_FRAME_POINTER := -fomit-frame-pointer
endif

# Optimization and language options.
FFLAGS := $(OMIT_FRAME_POINTER) -funit-at-a-time -finline-limit=2000000 \
          -fno-strict-aliasing -fno-threadsafe-statics \
          -fnon-call-exceptions

# Warning options.
WFLAGS := -Wall -Wpointer-arith -Wcast-align -Wwrite-strings \
          -Wno-parentheses -Wno-conversion $(WERROR)

# Flags for C++ compilation.
CFLAGS := --std=c++11 $(INCLUDES) $(OPT) $(FFLAGS) $(WFLAGS) $(PM) -MP -MMD

# Default rule for building an object file from a C++ file.
%.o: %.cc $(MAKEFILE_LIST)
	$(CC) $(CFLAGS) -o $@ -c $<

jarvis_demo_setup:jarvis_demo_setup.o
	$(CC) -o $@ $< $(LIBS) -ljarvis -ljarvis-util -lstdc++

jarvis_demo_server:jarvis_demo_server.o
	$(CC) -o $@ $< $(LIBS) -ljarvis -ljarvis-util -lstdc++ $(EXTRA_LIBS)

jarvis_demo_client:jarvis_demo_client.o
	$(CC) -o $@ $< $(LIBS) -ljarvis -ljarvis-util -lstdc++ $(EXTRA_LIBS)


.PHONY: all

clean:
	rm -f jarvis_demo_server jarvis_demo_server.o jarvis_demo_client\
 jarvis_demo_client.o jarvis_demo_setup jarvis_demo_setup.o